export {
  EngineLimitError,
  EngineSafetyError,
  ParseError,
  evaluateQuerySpecWithProof,
  isAggregateRule,
  isComparison,
  isIntegrityConstraint,
  isNegation,
  parseProgram,
  parseQuerySpec,
  serializeClause,
  serializeTerm,
  type Clause,
  type Goal,
  type Literal,
  type ProofStep,
  type QueryProof,
  type QuerySpec,
  type Term,
} from "../../src/engine/index.js";
