export {
  type Clause,
  type AggregateOperator,
  type AggregateRuleClause,
  type AggregateRuleSpec,
  type AggregateQuerySpec,
  type ArithmeticOp,
  type BinaryArithmeticExpression,
  type CmpOp,
  type Comparison,
  type Goal,
  type IntegrityConstraintClause,
  type Literal,
  type Negation,
  type OrdinaryClause,
  type QuerySpec,
  type RelationalQuerySpec,
  type ScalarExpression,
  type Term,
  type UnaryArithmeticExpression,
  type UnaryArithmeticOp,
  MAX_ARITHMETIC_EXPRESSION_DEPTH,
  MAX_ARITHMETIC_EXPRESSION_NODES,
  canonicalKey,
  isArithmeticExpression,
  isAggregateRule,
  isComparison,
  isIntegrityConstraint,
  isNegation,
  predKey,
  serializeClause,
  serializeGoal,
  serializeQuerySpec,
  serializeScalarExpression,
  serializeTerm,
} from './ast.js';
export {
  type AbsenceProof,
  type AggregateContribution,
  type AggregateProof,
  type Bindings,
  type DerivationProof,
  type EvaluationMetrics,
  type ExplainedBindings,
  type ExplainedQueryBindings,
  type EvaluateOptions,
  type MaterializedFactWithProof,
  type MaterializedFact,
  type ProofStep,
  type QueryProof,
  DEFAULT_MAX_PROOF_ENUMERATION_STEPS,
  DEFAULT_MAX_PROOFS_PER_ROW,
  EngineLimitError,
  EngineSafetyError,
  MAX_PROOF_ENUMERATION_STEPS,
  MAX_PROOFS_PER_ROW,
  evaluate,
  comparisonMatches,
  evaluateQuerySpec,
  evaluateQuerySpecWithProof,
  evaluateWithProof,
  literalMatches,
  materializeWithProof,
  materialize,
} from './evaluate.js';
export {
  CLOSURE_SUFFIX,
  closureBasePredicate,
  closureClauses,
  expandClosurePredicates,
} from './closure.js';
export { ParseError } from './lexer.js';
export { parseProgram, parseQuery, parseQuerySpec } from './parser.js';
export { parseQueryProgram, type QueryProgram } from './query-program.js';
export {
  diagnoseQuery,
  type DiagnoseOptions,
  type QueryDiagnostic,
} from './diagnostics.js';
export {
  StratificationError,
  stratifyProgram,
  type StratifiedProgram,
  type StratifiedRule,
} from './stratify.js';
