#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ── RunPod Serverless setup for the reader training worker ────────────────
# Produces RUNPOD_API_KEY, RUNPOD_VOLUME_ID, RUNPOD_DATACENTER, RUNPOD_S3_ACCESS_KEY,
# RUNPOD_S3_SECRET_KEY and DOCKER_HUB_USERNAME in .env, then checks the S3 key against the
# volume. The endpoint itself is created afterwards from the API key (benchmarks/runpod/README.md).
TOTAL_STAGES=4

banner "RunPod Serverless setup"

stage "RunPod: API key"
say "The submit script and the endpoint creation call the RunPod API with this key."
open_url "https://console.runpod.io/user/settings"
step "Open the 'API Keys' section, click 'Create API Key', name it rembero-reader, permission Read/Write."
step "Copy the key when it is shown; it is not shown again."
ask_secret RUNPOD_API_KEY "Paste the RunPod API key:"
write_env RUNPOD_API_KEY "$RUNPOD_API_KEY"

stage "RunPod: network volume"
say "Training data, the resume checkpoint, the base model cache and the finished GGUF live on a network volume the worker mounts at /runpod-volume."
open_url "https://console.runpod.io/user/storage"
step "Click 'New Network Volume'. Pick a datacenter that lists H100 80GB as available for Serverless (the datacenter pins the endpoint)."
step "Name: rembero-reader. Size: 40 GB (about \$2.80 a month; delete it when the runs are done)."
step "After it is created, the list shows its ID and its datacenter code (for example EU-RO-1 or US-TX-3)."
ask RUNPOD_VOLUME_ID "Paste the network volume ID:"
ask RUNPOD_DATACENTER "Type the datacenter code exactly as shown (e.g. EU-RO-1):"
write_env RUNPOD_VOLUME_ID "$RUNPOD_VOLUME_ID"
write_env RUNPOD_DATACENTER "$RUNPOD_DATACENTER"

stage "RunPod: S3 API key for the volume"
say "Files move to and from the volume through RunPod's S3-compatible API, which uses its own key pair."
open_url "https://console.runpod.io/user/settings"
step "Open the 'S3 API Keys' section, click 'Create', name it rembero-reader."
step "Copy both the access key and the secret; the secret is shown once."
ask RUNPOD_S3_ACCESS_KEY "Paste the S3 access key:"
ask_secret RUNPOD_S3_SECRET_KEY "Paste the S3 secret key:"
write_env RUNPOD_S3_ACCESS_KEY "$RUNPOD_S3_ACCESS_KEY"
write_env RUNPOD_S3_SECRET_KEY "$RUNPOD_S3_SECRET_KEY"
step "Checking the key against the volume (lists the bucket; empty is fine)..."
if RUNPOD_S3_ACCESS_KEY="$RUNPOD_S3_ACCESS_KEY" RUNPOD_S3_SECRET_KEY="$RUNPOD_S3_SECRET_KEY" \
   RUNPOD_VOLUME_ID="$RUNPOD_VOLUME_ID" RUNPOD_DATACENTER="$RUNPOD_DATACENTER" \
   .venv/bin/python - <<'PY'
import os, boto3
dc = os.environ["RUNPOD_DATACENTER"]
s3 = boto3.client("s3", endpoint_url=f"https://s3api-{dc.lower()}.runpod.io/", region_name=dc,
                  aws_access_key_id=os.environ["RUNPOD_S3_ACCESS_KEY"], aws_secret_access_key=os.environ["RUNPOD_S3_SECRET_KEY"])
r = s3.list_objects_v2(Bucket=os.environ["RUNPOD_VOLUME_ID"], MaxKeys=5)
print("  ok:", r.get("KeyCount", 0), "objects on the volume")
PY
then note "S3 access works."; else warn "The S3 check failed. Re-check the datacenter code and the two keys; the endpoint is https://s3api-<datacenter>.runpod.io/. You can re-run this wizard; values already saved are offered as defaults."; pause; fi

stage "Docker Hub: where the worker image is pushed"
say "RunPod pulls the worker image from Docker Hub. The build is local; only the push needs your account."
open_url "https://hub.docker.com/settings/general"
step "Note your Docker Hub username (top right, or on this settings page)."
ask DOCKER_HUB_USERNAME "Docker Hub username:"
write_env DOCKER_HUB_USERNAME "$DOCKER_HUB_USERNAME"
step "Logging Docker into Docker Hub (enter your Docker Hub password or an access token when asked)..."
docker login -u "$DOCKER_HUB_USERNAME" || warn "docker login failed; run 'docker login -u $DOCKER_HUB_USERNAME' yourself before the push."

finish
