export * from './engine/index.js';
export {
  MemoryStore,
  defaultRoot,
  type AssertResult,
  type MemorySource,
  type TemporalMemorySource,
  type MutationContext,
  type IdempotentMutationOperation,
  type ValidTimeMode,
  type SupersedeResult,
  type RuleChangeCandidateView,
  type RuleChangeMutationRequest,
  type RuleChangeMutationResult,
  type MemoryChangeTemporalArchive,
  type MemoryChangeMutationRequest,
  type MemoryChangeMutationResult,
  type MemoryHistoryAction,
  type MemoryHistoryEvent,
  type MemoryHistory,
  type MemoryHistoryOptions,
  type RecordedSnapshotMetadata,
  type RecordedKnowledgeSnapshot,
  type CurrentKnowledgeSnapshot,
  type JournalCheckpointNamespace,
  type JournalCheckpointArtifact,
  type JournalCompactionOptions,
  type JournalCompactionResult,
  MAX_HISTORY_EVENTS,
  MAX_OPERATION_ID_BYTES,
  MAX_JOURNAL_SEGMENTS,
  MAX_TOTAL_JOURNAL_ENTRIES,
  MAX_CHECKPOINT_BYTES,
  MAX_RECORDED_SNAPSHOT_BATCH,
  MAX_SUPERSEDE_PATTERNS,
  MAX_RULE_CHANGE_RULES,
  MAX_MEMORY_CHANGE_CLAUSES,
  knowledgeProgramDigest,
  OperationConflictError,
  RuleChangeStaleError,
  MemoryChangeStaleError,
  IncompleteHistoryError,
  type AutoCaptureBatch,
  type AutoCaptureFact,
  type AutoCaptureReview,
  type AutoCaptureReviewOptions,
  type AutoCaptureReservation,
  type AutoCaptureReservationRequest,
  type AutoCaptureStatus,
  type PruneAutoCaptureOptions,
} from './store/store.js';
export {
  createSqliteMemoryStore,
  type SqliteMemoryStore,
  type SqliteMemoryStoreOptions,
} from './store/sqlite-store.js';
export * from './ledger/semantic-ledger.js';
export * from './ledger/knowledge-version.js';
export {
  DatalogDatabase,
  buildSqliteExtension,
  openDatalogDatabase,
  openRememberoDatabase,
  resolveSqliteExtensionPath,
  sqliteDatalogExecutionMode,
  type DatalogRow,
  type DatalogExplanation,
  type DatalogProof,
  type RememberoDatabase,
  type RememberoDatabaseMethods,
  type OpenRememberoDatabaseOptions,
  type OpenDatalogDatabaseOptions,
  type SqliteDatalogExecutionMode,
  type SqliteDatalogPlanColumn,
  type SqliteDatalogPlanRelation,
  type SqliteDatalogPlanDerivedPredicate,
  type SqliteDatalogPlan,
} from './sqlite/extension.js';
export {
  type ChatMessage,
  type LlmClient,
  type LlmConfig,
  type LlmCompletion,
  type LlmCompletionOptions,
  type LlmUsage,
  type LlmUsageTotals,
  DEFAULT_MODEL,
  OpenRouterClient,
  addLlmUsage,
  clientFromEnv,
  emptyLlmUsageTotals,
  lazyClientFromEnv,
} from './llm/client.js';
export {
  type PipelineDeps,
  type RecallOptions,
  type RecallPruningReport,
  type RecallQueryReview,
  type RecallQueryReviewReason,
  type RecallResult,
  type RecallRelatedKnowledgeOptions,
  type RecallWhyNotUnavailable,
  type RecallSchemaAttempt,
  type RecallSchemaAttemptOutcome,
  type RecallStatus,
  type RecallAnswerMode,
  type RememberResult,
  type RememberExtraction,
  type RememberOptions,
  type RememberTranscriptOptions,
  type RetrievalResult,
  recallQuestion,
  deterministicRecallAnswer,
  evidenceRecallAnswer,
  rememberTranscriptText,
  rememberText,
  extractRememberText,
  retrieveQuestion,
} from './llm/pipeline.js';
export {
  proposeRememberText,
  computeMemoryProposalDigest,
  MEMORY_PROPOSAL_VERSION,
  type ProposeRememberOptions,
  type MemoryChangeProposal,
  type ProposeRememberResult,
} from './knowledge/memory-proposal.js';
export {
  parseMemoryProposal,
  applyMemoryProposal,
  MAX_MEMORY_PROPOSAL_BYTES,
  MemoryChangeCheckError,
  type ApplyMemoryProposalOptions,
  type ApplyMemoryProposalResult,
} from './knowledge/memory-application.js';
export {
  inspectKnowledgeHealth,
  MAX_KNOWLEDGE_HEALTH_FINDINGS,
  MAX_KNOWLEDGE_HEALTH_UNSOURCED,
  type KnowledgeHealthStatus,
  type KnowledgeHealthSeverity,
  type KnowledgeHealthCode,
  type KnowledgeHealthFinding,
  type KnowledgeHealthOptions,
  type KnowledgeHealthResult,
} from './knowledge/health.js';
export {
  enforceKnowledgeCheckCandidate,
  KnowledgeCheckEnforcementError,
  type KnowledgeCheckEnforcementMode,
  type KnowledgeCheckEnforcementOptions,
  type KnowledgeCheckEnforcementDelta,
} from './knowledge/check-enforcement.js';
export {
  type QueryPromptVariant,
  transcriptExtractionSystemPrompt,
} from './llm/prompts.js';
export {
  DEFAULT_RECALL_SCHEMA_BYTES,
  DEFAULT_RECALL_SCHEMA_PREDICATES,
  MAX_RECALL_SCHEMA_BYTES,
  MAX_RECALL_SCHEMA_CANDIDATES,
  MAX_RECALL_SCHEMA_CLAUSES,
  MAX_RECALL_SCHEMA_PREDICATES,
  MAX_RECALL_QUESTION_WORDS,
  MAX_RECALL_SOURCE_RANKING_CHARS,
  RecallSchemaBudgetError,
  type RecallSchemaDiagnostics,
  type RecallSchemaOptions,
  type RecallSchemaSelection,
  recallSchemaDiagnostics,
  selectRecallSchema,
} from './llm/schema.js';
export {
  autoCaptureClaudeStop,
  type AutoCaptureDeps,
  type AutoCaptureOptions,
  type AutoCaptureResult,
} from './autocapture/capture.js';
export {
  DEFAULT_AUTO_CAPTURE_DAILY_CAP,
  MANAGED_HOOK_MARKER,
  MAX_AUTO_CAPTURE_DAILY_CAP,
  defaultClaudeSettingsPath,
  installClaudeHook,
  removeClaudeHook,
  validateAutoCaptureDailyCap,
  validateAutoCaptureTailBytes,
  type HookChangeResult,
  type InstallClaudeHookOptions,
  type RemoveClaudeHookOptions,
} from './autocapture/hooks.js';
export {
  DEFAULT_TRANSCRIPT_TAIL_BYTES,
  MAX_TRANSCRIPT_TAIL_BYTES,
  defaultClaudeConfigDir,
  parseClaudeStopHookInput,
  readClaudeTranscriptTail,
  type ClaudeStopHookInput,
  type ClaudeTranscriptTail,
  type TranscriptReadOptions,
} from './autocapture/transcript.js';
export { createServer, serveStdio } from './mcp/server.js';
export {
  AGENT_DB_SCORECARD_VERSION,
  buildAgentDbScorecard,
  type AgentDbScorecard,
} from './evals/agent-db-scorecard.js';
export {
  runAgentDbScaleSweep,
  type AgentDbScaleCase,
  type AgentDbScaleSweep,
} from './evals/agent-db-scale.js';
export {
  RememberoWebService,
  RemberoWebService,
  WebServiceError,
  GUIDED_QUESTIONS,
  WEB_DEMO_NAMESPACE,
  type GuidedQuestion,
  type RememberoWebServiceOptions,
  type RemberoWebServiceOptions,
} from './web/service.js';
export { startWebServer, type StartWebServerOptions } from './web/server.js';
export {
  DEFAULT_UNLIMITED_OCR_MODEL,
  UNLIMITED_OCR_PROMPT,
  UNLIMITED_OCR_MAX_TOKENS,
  UNLIMITED_OCR_SINGLE_PAGE_WINDOW,
  UNLIMITED_OCR_MULTI_PAGE_WINDOW,
  UNLIMITED_OCR_NGRAM_SIZE,
  UNLIMITED_OCR_MAX_IMAGES,
  UNLIMITED_OCR_MAX_IMAGE_BYTES,
  UNLIMITED_OCR_MAX_TOTAL_IMAGE_BYTES,
  UNLIMITED_OCR_MAX_RESPONSE_BYTES,
  UNLIMITED_OCR_MAX_OUTPUT_CHARS,
  UNLIMITED_OCR_MAX_GROUNDING_BLOCKS,
  UNLIMITED_OCR_DEFAULT_TIMEOUT_MS,
  UnlimitedOcrClient,
  parseUnlimitedOcrGrounding,
  type UnlimitedOcrClientOptions,
  type UnlimitedOcrGroundingBlock,
  type UnlimitedOcrImageInput,
  type UnlimitedOcrParseResult,
} from './document/unlimited-ocr.js';
export {
  LIVE_OCR_EVIDENCE,
  type LiveOcrDocumentEvidence,
  type LiveOcrEvidenceMetric,
  type LiveOcrEvidenceSnapshot,
} from './document/live-ocr-evidence.js';
export {
  PRODUCT_SHIP_EVIDENCE,
  type ProductShipEvidence,
  type ProductShipModelEvidence,
} from './document/product-ship-evidence.js';
export {
  DOCUMENT_MEMORG_FORMAT,
  DOCUMENT_MEMORG_VERSION,
  DOCUMENT_MEMORG_TARGET_VERSION,
  DOCUMENT_MEMORG_ROOT_KEY,
  createDocumentMemorgExport,
  serializeDocumentMemorgExport,
  verifyDocumentMemorgExport,
  type DocumentMemorgAuthority,
  type DocumentMemorgExport,
  type DocumentMemorgItem,
  type DocumentMemorgItemType,
  type DocumentMemorgVerification,
} from './document/memorg.js';
export {
  type AbsenceGraphNode,
  type AggregateGraphNode,
  buildExplanationGraph,
  explainKnowledge,
  type ClaimGraphNode,
  type ConflictGraphNode,
  type EntityGraphNode,
  type ExplainKnowledgeOptions,
  type ExplainKnowledgeResult,
  type ExplainedKnowledgeRow,
  type ExplanationGraph,
  type ExplanationGraphEdge,
  type ExplanationGraphNode,
  type ExplanationRule,
  type ProofGraphNode,
  type ResultGraphNode,
  type SourcedDerivationProof,
  type SourcedAbsenceProof,
  type SourcedAggregateProof,
  type SourcedProofStep,
  type SourcedQueryProof,
} from './knowledge/graph.js';
export {
  inspectConflicts,
  MAX_CONFLICT_FOCUS_BYTES,
  type ConflictCluster,
  type ConflictConstraint,
  type ConflictViolation,
  type ConflictViewOptions,
  type ConflictViewResult,
} from './knowledge/conflicts.js';
export {
  simulateKnowledge,
  captureCounterfactualBaseline,
  applyCounterfactualChanges,
  buildCounterfactualKnowledgeView,
  evaluateCounterfactualKnowledgeView,
  MAX_COUNTERFACTUAL_ASSUMPTIONS,
  MAX_COUNTERFACTUAL_RETRACTIONS,
  MAX_COUNTERFACTUAL_RULE_ADDITIONS,
  MAX_COUNTERFACTUAL_RULE_REMOVALS,
  type CounterfactualKnowledgeOptions,
  type CounterfactualViewOptions,
  type CounterfactualBaseline,
  type CounterfactualKnowledgeView,
  type CounterfactualKnowledgeResult,
  type CounterfactualApplication,
  type CounterfactualResultDelta,
  type CounterfactualIntegrityDelta,
  type CounterfactualIntegrityViolation,
  type CounterfactualRuleAuditDelta,
  type CounterfactualCheckDelta,
  type RuleChangeProposal,
  computeRuleChangeProposalDigest,
} from './knowledge/counterfactual.js';
export {
  parseRuleChangeProposal,
  applyRuleChangeProposal,
  RULE_CHANGE_PROPOSAL_VERSION,
  MAX_RULE_CHANGE_PROPOSAL_BYTES,
  RuleChangeCheckError,
  type ApplyRuleChangeProposalOptions,
  type ApplyRuleChangeProposalResult,
} from './knowledge/rule-change.js';
export {
  explainWhyNot,
  summarizeWhyNot,
  DEFAULT_MAX_WHY_NOT_FAILURES,
  MAX_WHY_NOT_FAILURES,
  DEFAULT_MAX_WHY_NOT_DEPTH,
  MAX_WHY_NOT_DEPTH,
  DEFAULT_MAX_WHY_NOT_CANDIDATES,
  MAX_WHY_NOT_CANDIDATES,
  DEFAULT_MAX_WHY_NOT_EVIDENCE,
  MAX_WHY_NOT_EVIDENCE,
  DEFAULT_WHY_NOT_SUMMARY_FAILURES,
  MAX_WHY_NOT_SUMMARY_FAILURES,
  type WhyNotReason,
  type WhyNotStatus,
  type WhyNotObservedFact,
  type WhyNotRuleAttempt,
  type WhyNotFailure,
  type WhyNotGraphNode,
  type WhyNotGraphEdge,
  type WhyNotGraph,
  type ExplainWhyNotOptions,
  type ExplainWhyNotResult,
} from './knowledge/why-not.js';
export {
  analyzeKnowledgeTopology,
  MAX_TOPOLOGY_FACTS,
  MAX_TOPOLOGY_PREDICATES,
  MAX_TOPOLOGY_RULES,
  MAX_TOPOLOGY_CONSTRAINTS,
  MAX_TOPOLOGY_EDGES,
  MAX_TOPOLOGY_FOCUS_BYTES,
  type TopologyDirection,
  type PredicateTopologyNode,
  type RuleTopologyNode,
  type ConstraintTopologyNode,
  type KnowledgeTopologyNode,
  type KnowledgeTopologyEdge,
  type KnowledgeTopologyGraph,
  type RecursivePredicateComponent,
  type KnowledgeTopologySelection,
  type AnalyzeKnowledgeTopologyOptions,
  type KnowledgeTopologyResult,
} from './knowledge/topology.js';
export {
  diffRecordedKnowledge,
  MAX_RECORDED_DIFF_CHANGES,
  type RecordedClauseKind,
  type RecordedClauseState,
  type RecordedClauseSourceChange,
  type RecordedClauseDelta,
  type RecordedTopologyNodeChange,
  type RecordedTopologyDelta,
  type RecordedIntegrityViolationChange,
  type RecordedIntegrityDelta,
  type RecordedQueryImpact,
  type RecordedKnowledgeDiffOptions,
  type RecordedKnowledgeDiffResult,
} from './knowledge/recorded-diff.js';
export {
  planKnowledgeRepair,
  DEFAULT_MAX_REPAIR_PLANS,
  MAX_REPAIR_PLANS,
  DEFAULT_MAX_REPAIR_STEPS,
  MAX_REPAIR_STEPS,
  DEFAULT_MAX_REPAIR_SEARCH_STATES,
  MAX_REPAIR_SEARCH_STATES,
  type RepairPlanStatus,
  type RepairPlanOptions,
  type VerifiedRepairPlan,
  type RepairPlanResult,
} from './knowledge/repair.js';
export {
  auditKnowledgeRules,
  MAX_RULE_AUDIT_FINDINGS,
  type RuleAuditSeverity,
  type RuleAuditStatus,
  type RuleAuditCode,
  type RuleAuditFinding,
  type RuleAuditFindingNode,
  type RuleAuditGraphNode,
  type RuleAuditGraphEdge,
  type RuleAuditGraph,
  type AuditKnowledgeRulesOptions,
  type RuleAuditResult,
} from './knowledge/rule-audit.js';
export {
  searchKnowledge,
  DEFAULT_KNOWLEDGE_SEARCH_LIMIT,
  DEFAULT_KNOWLEDGE_SEARCH_SOURCE_CHARS,
  MAX_KNOWLEDGE_SEARCH_LIMIT,
  MAX_KNOWLEDGE_SEARCH_CLAUSES,
  MAX_KNOWLEDGE_SEARCH_SOURCE_CHARS,
  MAX_KNOWLEDGE_SEARCH_TOTAL_SOURCE_CHARS,
  MAX_KNOWLEDGE_SEARCH_WORDS,
  type KnowledgeSearchClauseKind,
  type KnowledgeSearchReasonKind,
  type KnowledgeSearchReason,
  type KnowledgeSearchResultItem,
  type KnowledgeSearchGraphNode,
  type KnowledgeSearchGraphEdge,
  type KnowledgeSearchGraph,
  type KnowledgeSearchOptions,
  type KnowledgeSearchResult,
} from './knowledge/search.js';
export {
  semanticSearchKnowledge,
  prepareSemanticKnowledge,
  semanticDocumentText,
  semanticDocumentChunks,
  semanticEmbeddingCacheKey,
  isRecommendationIntent,
  MemoryEmbeddingCache,
  FileEmbeddingCache,
  LayeredEmbeddingCache,
  DEFAULT_SEMANTIC_SEARCH_CANDIDATES,
  MAX_SEMANTIC_SEARCH_CANDIDATES,
  MAX_SEMANTIC_SOURCE_CHARS,
  DEFAULT_SEMANTIC_CACHE_ENTRIES,
  MAX_SEMANTIC_CACHE_ENTRY_BYTES,
  SEMANTIC_CACHE_VERSION,
  DEFAULT_SEMANTIC_PREPARE_LIMIT,
  MAX_SEMANTIC_PREPARE_LIMIT,
  SEMANTIC_CHUNK_CHARACTERS,
  SEMANTIC_CHUNK_OVERLAP,
  MAX_SEMANTIC_CHUNKS_PER_DOCUMENT,
  SEMANTIC_LEXICAL_GUARD_RATIO,
  SEMANTIC_LEXICAL_GUARD_MIN_SCORE,
  type EmbeddingCache,
  type PrepareSemanticKnowledgeOptions,
  type PrepareSemanticKnowledgeResult,
  type SemanticKnowledgeSearchOptions,
  type SemanticKnowledgeSearchResult,
  type SemanticKnowledgeSearchResultItem,
} from './knowledge/semantic-search.js';
export {
  OpenRouterEmbeddingClient,
  embeddingClientFromEnv,
  lazyEmbeddingClientFromEnv,
  DEFAULT_EMBEDDING_MODEL,
  MAX_EMBEDDING_INPUTS,
  MAX_EMBEDDING_DIMENSIONS,
  type EmbeddingClient,
  type EmbeddingConfig,
  type EmbeddingResult,
  type EmbeddingUsage,
} from './llm/embeddings.js';
export {
  browseKnowledgeGraph,
  DEFAULT_BROWSE_GRAPH_DEPTH,
  MAX_BROWSE_GRAPH_DEPTH,
  DEFAULT_BROWSE_GRAPH_CLAIMS,
  MAX_BROWSE_GRAPH_CLAIMS,
  MAX_BROWSE_GRAPH_NODES,
  MAX_BROWSE_GRAPH_FACTS,
  MAX_BROWSE_PREDICATE_FOCUS_BYTES,
  MAX_BROWSE_ENTITY_FOCUS_BYTES,
  type BrowseKnowledgeGraphOptions,
  type BrowseKnowledgeGraphSelection,
  type BrowseKnowledgeGraphResult,
} from './knowledge/browse.js';
export {
  connectKnowledgeGraph,
  DEFAULT_KNOWLEDGE_PATH_DEPTH,
  MAX_KNOWLEDGE_PATH_DEPTH,
  DEFAULT_KNOWLEDGE_PATHS,
  MAX_KNOWLEDGE_PATHS,
  type ConnectKnowledgeGraphOptions,
  type KnowledgeGraphPathSegment,
  type KnowledgeGraphPath,
  type KnowledgePathClaimProof,
  type ConnectKnowledgeGraphSelection,
  type ConnectKnowledgeGraphResult,
} from './knowledge/paths.js';
export {
  createKnowledgeBundle,
  serializeKnowledgeBundle,
  verifyKnowledgeBundle,
  KNOWLEDGE_BUNDLE_FORMAT,
  KNOWLEDGE_BUNDLE_VERSION,
  MAX_KNOWLEDGE_BUNDLE_BYTES,
  MAX_KNOWLEDGE_BUNDLE_NAMESPACES,
  MAX_KNOWLEDGE_BUNDLE_CLAUSES,
  MAX_KNOWLEDGE_BUNDLE_SOURCES,
  type KnowledgeBundleView,
  type KnowledgeBundleClause,
  type KnowledgeBundleNamespace,
  type KnowledgeBundle,
  type CreateKnowledgeBundleOptions,
  type KnowledgeBundleVerification,
} from './knowledge/bundle.js';
export {
  parseKnowledgeCheckSuite,
  runKnowledgeChecks,
  KNOWLEDGE_CHECK_SUITE_VERSION,
  MAX_KNOWLEDGE_CHECK_SUITE_BYTES,
  MAX_KNOWLEDGE_CHECKS,
  MAX_KNOWLEDGE_CHECK_NAME_BYTES,
  MAX_KNOWLEDGE_CHECK_EXPECTED_ROWS,
  MAX_KNOWLEDGE_CHECK_BINDINGS,
  type KnowledgeCheckExpectation,
  type KnowledgeCheck,
  type KnowledgeCheckSuite,
  type KnowledgeCheckCoverageRequirement,
  type KnowledgeCheckResult,
  type RunKnowledgeChecksOptions,
  type KnowledgeCheckSuiteResult,
  type KnowledgeRuleCoverageEntry,
  type KnowledgeRuleCoverage,
} from './knowledge/checks.js';
export {
  profileKnowledge,
  type ProfileKnowledgeOptions,
  type KnowledgeWorkReduction,
  type ProfileKnowledgeResult,
} from './knowledge/profile.js';
export {
  TENTATIVE_PREDICATE,
  MAX_TENTATIVE_FACTS,
  MAX_TENTATIVE_CLAUSE_BYTES,
  TrustMetadataError,
  assertTrustMetadataSafety,
  decodeTentativeDeclaration,
  isTentativeDeclaration,
  isTrustMetadataPredicate,
  listTentativeClaims,
  projectTrustKnowledge,
  tentativeClaimId,
  wrapTentativeFacts,
  type KnowledgeTrust,
  type TentativeClaim,
  type TentativeResolutionAction,
  type TrustKnowledgeView,
  type TrustProjection,
  type TrustViewMode,
} from './knowledge/trust.js';
export {
  MAX_TENTATIVE_REVIEW_CLAIMS,
  assertTentativeFacts,
  resolveTentativeFacts,
  reviewTentativeClaims,
  type StoredTentativeClaim,
  type TentativeAssertionResult,
  type TentativeResolutionResult,
} from './knowledge/trust-store.js';
export {
  MAX_GRAPH_NEIGHBOR_DEPTH,
  MAX_GRAPH_NODE_ID_BYTES,
  MAX_GRAPH_RESULT_ROW,
  selectExplanationGraph,
  selectKnowledgeGraph,
  type ExplanationGraphSelection,
  type ExplanationGraphSelector,
  type GraphSelectableExplanation,
} from './knowledge/graph-navigation.js';
export {
  ENTITY_ALIAS_PREDICATE,
  ENTITY_POSITION_PREDICATE,
  MAX_ENTITY_ALIASES,
  MAX_ENTITY_POSITIONS,
  EntityIdentityError,
  EntityResolver,
  buildEntityResolver,
  canonicalizeKnowledge,
  isEntityMetadataDeclaration,
  isEntityMetadataPredicate,
  literalKnowledge,
  type CanonicalKnowledgeView,
  type EntityAlias,
  type EntityIdentityMode,
  type EntityPosition,
  type EntityProjection,
  type EntityRewrite,
} from './knowledge/identity.js';
export {
  checkIntegrity,
  DEFAULT_MAX_INTEGRITY_VIOLATIONS,
  MAX_INTEGRITY_CONSTRAINTS,
  MAX_INTEGRITY_VIOLATIONS,
  type IntegrityCheckOptions,
  type IntegrityCheckResult,
  type IntegrityConstraintCheck,
  type IntegrityStatus,
} from './knowledge/integrity.js';
export {
  enforceIntegrityCandidate,
  IntegrityViolationError,
  type IntegrityEnforcementMode,
  type IntegrityEnforcementOptions,
  type IntegrityViolationRef,
} from './knowledge/enforcement.js';
